version: "3.7"

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MYSQL_PASSWORD:
    external: true
  MYSQL_ROOT_PASSWORD:
    external: true

networks:
  network:

volumes:
  static-volume:
  media-volume:
  maria-database:

services:
  mariadb:
    image: mariadb:10.5
    networks:
      - network
    volumes:
      - maria-database:/var/lib/mysql
    secrets:
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    environment:
      MYSQL_DATABASE: django
      MYSQL_USER: django
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD


  django_container_gunicorn:
    image: lklk_deploy_image:1
    networks:
      - network
    volumes:
      - static-volume:/home/LKLK/staticfiles/
      - media-volume:/home/LKLK/media/
    secrets:
      - MYSQL_PASSWORD
      - DJANGO_SECRET_KEY


  nginx:
    image: nginx:latest
    networks:
      - network
    volumes:
      - /home/django_course/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/data/static/
      - media-volume:/data/media/
    ports:
      - 80:80